# Generated by Django 2.2.5 on 2020-11-06 11:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Owner_name', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(null=True)),
                ('trans_id', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100)),
                ('cus_type', models.CharField(max_length=100, null=True)),
                ('trans_id', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(null=True)),
                ('Address', models.TextField(null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='Currency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cus_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
