# Generated by Django 2.2.5 on 2020-11-06 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201106_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 11, 46, 19, 183398, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_detail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 11, 46, 36, 596070, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_detail',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 11, 46, 40, 829879, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_order',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
