# Generated by Django 2.2.5 on 2020-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20201106_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_detail',
            old_name='Owner_name',
            new_name='Customer_name',
        ),
    ]
