# Generated by Django 2.2.5 on 2020-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20201108_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='Subscription_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
