# Generated by Django 2.2.5 on 2020-10-26 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listofdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Listofpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Listoflab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, null=True)),
                ('business_start', models.CharField(max_length=100, null=True)),
                ('noof_employee', models.IntegerField(null=True)),
                ('work_days', models.IntegerField(null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('landline_no', models.IntegerField(null=True)),
                ('lab_email', models.CharField(max_length=100, null=True)),
                ('lab_logo', models.ImageField(blank=True, upload_to='images/')),
                ('lab_image', models.ImageField(blank=True, upload_to='images/')),
                ('service_provider', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('packagetest_list', models.TextField(null=True)),
                ('aboutlab_description', models.TextField(null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labprofile.Listofpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Labentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, null=True)),
                ('business_start', models.CharField(max_length=100, null=True)),
                ('noof_employee', models.IntegerField(null=True)),
                ('work_days', models.IntegerField(null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('landline_no', models.IntegerField(null=True)),
                ('lab_email', models.CharField(max_length=100, null=True)),
                ('lab_logo', models.ImageField(blank=True, upload_to='images/')),
                ('lab_image', models.ImageField(blank=True, upload_to='images/')),
                ('service_provider', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('packagetest_list', models.TextField(null=True)),
                ('aboutlab_description', models.TextField(null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labprofile.Listofpackage')),
            ],
        ),
    ]
