# Generated by Django 2.2.5 on 2020-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labentry',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofdoctor',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listoflab',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofpackage',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
