# Generated by Django 2.2.5 on 2020-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0004_auto_20201028_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='doc_image',
            new_name='package_image',
        ),
        migrations.AddField(
            model_name='labentry',
            name='lab_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labentry',
            name='lab_logo_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labentry',
            name='lab_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labentry',
            name='video_upload',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='listoflab',
            name='video_upload',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='video_upload',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
