# Generated by Django 2.2.5 on 2020-10-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0005_auto_20201028_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labentry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labprofile.Package'),
        ),
        migrations.DeleteModel(
            name='Listoflab',
        ),
        migrations.DeleteModel(
            name='Listofpackage',
        ),
    ]
