# Generated by Django 2.2.5 on 2020-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0007_auto_20201029_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
