# Generated by Django 2.2.5 on 2020-10-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0008_package_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labentry',
            old_name='noof_employee',
            new_name='no_of_employee',
        ),
    ]
