# Generated by Django 2.2.5 on 2020-10-31 07:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0009_auto_20201029_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listoflabbooking',
            old_name='package_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='listoflabbooking',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listoflabbooking',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='listoflabbooking',
            name='profile_for',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
