# Generated by Django 2.2.5 on 2020-10-31 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0011_auto_20201031_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labentry',
            old_name='aboutlab_description',
            new_name='package_test_list',
        ),
        migrations.RemoveField(
            model_name='labentry',
            name='packagetest_list',
        ),
        migrations.AddField(
            model_name='labentry',
            name='about_lab_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
