# Generated by Django 2.2.5 on 2020-11-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labprofile', '0012_auto_20201031_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labentry',
            new_name='Lab_entry',
        ),
        migrations.RenameModel(
            old_name='Listoflabbooking',
            new_name='List_of_lab_booking',
        ),
    ]
