# Generated by Django 2.2.5 on 2020-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_check',
            name='image_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='meta_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='health_check',
            name='video_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health_check',
            name='video_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
