# Generated by Django 2.2.5 on 2020-11-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeyourorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placeyourorder',
            new_name='Place_your_order',
        ),
    ]
