# Generated by Django 2.2.5 on 2020-10-31 08:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scanprofile', '0002_auto_20201031_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanentry',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
