# Generated by Django 2.2.5 on 2020-10-31 12:38

import ckeditor.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('scanprofile', '0003_auto_20201031_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanentry',
            name='aboutlab_description',
        ),
        migrations.AddField(
            model_name='scanentry',
            name='about_lab_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanbooking',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
