# Generated by Django 2.2.5 on 2020-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('speciality', models.CharField(max_length=20, null=True)),
                ('doctor_image', models.ImageField(blank=True, upload_to='images/')),
                ('clinic_name', models.CharField(max_length=20, null=True)),
                ('clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('working_days', models.CharField(max_length=20, null=True)),
                ('morning_timing', models.CharField(max_length=20, null=True)),
                ('evening_timing', models.CharField(max_length=20, null=True)),
                ('google_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=1)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listofdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('speciality', models.CharField(max_length=20, null=True)),
                ('doctor_image', models.ImageField(blank=True, upload_to='images/')),
                ('clinic_name', models.CharField(max_length=20, null=True)),
                ('clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('working_days', models.CharField(max_length=20, null=True)),
                ('morning_timing', models.CharField(max_length=20, null=True)),
                ('evening_timing', models.CharField(max_length=20, null=True)),
                ('google_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=1)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
