# Generated by Django 2.2.5 on 2020-10-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorentry',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctorentry',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='listofdoctor',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listofdoctor',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
