# Generated by Django 2.2.5 on 2020-10-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0002_auto_20201026_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorentry',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorentry',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listofdoctor',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=10),
        ),
    ]
