# Generated by Django 2.2.5 on 2020-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0004_auto_20201027_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorentry',
            name='clinic_alt_image',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorentry',
            name='doctor_alt_image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
