# Generated by Django 2.2.5 on 2020-10-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0005_auto_20201028_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listofdoctorbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('consulation', models.CharField(max_length=100, null=True)),
                ('patient_name', models.CharField(max_length=100, null=True)),
                ('profile_for', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
