# Generated by Django 2.2.5 on 2020-11-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorprofile', '0008_auto_20201031_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorentry',
            name='about_clinic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listofdoctor',
            name='about_clinic',
            field=models.TextField(null=True),
        ),
    ]
