# Generated by Django 2.2.5 on 2020-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_area_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
