# Generated by Django 2.2.5 on 2020-10-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20201027_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
