# Generated by Django 2.2.5 on 2020-10-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country'),
        ),
    ]
