# Generated by Django 2.2.5 on 2020-10-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Category_name', models.CharField(max_length=100, null=True)),
                ('Clinic_name', models.CharField(max_length=100, null=True)),
                ('Clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('Contact_person', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=20)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('video_upload', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=20, null=True)),
                ('video_alt_tag', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
