# Generated by Django 2.2.5 on 2020-10-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Addclinic',
        ),
    ]
