# Generated by Django 2.2.5 on 2020-10-31 09:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20201031_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
