# Generated by Django 2.2.5 on 2020-10-31 12:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addclinic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
