# Generated by Django 2.2.5 on 2020-11-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20201031_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addclinic',
            name='Category_name',
        ),
        migrations.AddField(
            model_name='addclinic',
            name='About_clinic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='addclinic',
            name='Category_type',
            field=models.CharField(choices=[('Drug Addiction Clinic', 'Drug Addiction Clinic'), ('STD Clinic', 'STD Clinic'), ('Nutrition Clinic', 'Nutrition Clinic'), ('Baby Clinic', 'Baby Clinic'), ('Urgent & Emergency Care Clinic', 'Urgent & Emergency Care Clinic'), ('Male Fertlity Clinic', 'Male Fertlity Clinic'), ('Female Fertlity Clinic', 'Female Fertlity Clinic'), ('Baby Adoption', 'Baby Adoption'), ('Poly Clinic', 'Poly Clinic')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicbooking',
            name='About_clinic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
