# Generated by Django 2.2.5 on 2020-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20201102_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='addclinic',
            name='Clinic_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
