# Generated by Django 2.2.5 on 2020-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20201111_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_clinic',
            name='meta_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='add_clinic',
            name='meta_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_clinic',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
