# Generated by Django 2.2.5 on 2020-11-10 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('lab_name', models.CharField(max_length=100, null=True)),
                ('lab_url', models.CharField(max_length=100, null=True)),
                ('subway_team', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('work_days', models.CharField(max_length=100, null=True)),
                ('package_image_url', models.CharField(max_length=100, null=True)),
                ('landline_no', models.IntegerField(null=True)),
                ('lab_email', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('total_price', models.IntegerField(null=True)),
            ],
        ),
    ]
