# Generated by Django 2.2.5 on 2020-11-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_extra_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field', models.CharField(max_length=100, null=True)),
                ('field', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='labs.Lab')),
            ],
        ),
    ]
