# Generated by Django 2.2.5 on 2020-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Page_name', models.CharField(max_length=100, null=True)),
                ('Page_url', models.CharField(max_length=100, null=True)),
                ('Error_Page', models.CharField(max_length=100, null=True)),
                ('Today_page', models.IntegerField(null=True)),
            ],
        ),
    ]
