# Generated by Django 2.2.5 on 2020-11-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_totalpage_trendingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpage',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Allpage'),
        ),
    ]
