# Generated by Django 2.2.5 on 2020-11-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_totalpage_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errorpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Page_name', models.CharField(max_length=100, null=True)),
                ('Page_url', models.CharField(max_length=100, null=True)),
                ('Page_id', models.CharField(max_length=100, null=True)),
                ('Total_page', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='totalpage',
            old_name='Total_page',
            new_name='Bounce_rate',
        ),
        migrations.RenameField(
            model_name='totalpage',
            old_name='Page_error',
            new_name='Error_Page',
        ),
        migrations.RenameField(
            model_name='trendingpage',
            old_name='Totay_page',
            new_name='Total_page',
        ),
        migrations.RenameField(
            model_name='trendingpage',
            old_name='Page_error',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='Page_error',
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='Page_maintained_by',
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='Page_url',
        ),
        migrations.RemoveField(
            model_name='otherpage',
            name='Totay_page',
        ),
        migrations.RemoveField(
            model_name='totalpage',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='trendingpage',
            name='Page_maintained_by',
        ),
        migrations.RemoveField(
            model_name='trendingpage',
            name='Page_name',
        ),
        migrations.RemoveField(
            model_name='trendingpage',
            name='Page_url',
        ),
        migrations.AddField(
            model_name='otherpage',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalpage',
            name='Today_page',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalpage',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trendingpage',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Allpage',
        ),
    ]
