# Generated by Django 2.2.5 on 2020-11-06 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20201106_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 14, 49, 11, 39411, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorpage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 14, 49, 16, 285917, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherpage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='totalpage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 14, 49, 23, 16626, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalpage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trendingpage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 6, 14, 49, 27, 198050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingpage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
