# Generated by Django 2.2.5 on 2020-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20201106_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorpage',
            old_name='Total_page',
            new_name='View_count',
        ),
        migrations.AddField(
            model_name='errorpage',
            name='Error_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='errorpage',
            name='Status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Unsolved', 'Unsolved')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='Meta_description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='Meta_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='Meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='otherpage',
            name='Page_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='errorpage',
            name='Page_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otherpage',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
