# Generated by Django 2.2.5 on 2020-11-09 13:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20201109_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpage',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
