# Generated by Django 2.2.5 on 2020-10-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospitalentry',
        ),
        migrations.DeleteModel(
            name='Hospitaltype',
        ),
        migrations.DeleteModel(
            name='Listofhospital',
        ),
        migrations.DeleteModel(
            name='Listofhospitaltype',
        ),
    ]
