# Generated by Django 2.2.5 on 2020-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitaldetails', '0002_auto_20201026_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitaltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listofhospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listofhospitaltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_type', models.CharField(max_length=100)),
            ],
        ),
    ]
