# Generated by Django 2.2.5 on 2020-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0003_hospitalentry_hospitaltype_listofhospital_listofhospitaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalentry',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofhospital',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
