# Generated by Django 2.2.5 on 2020-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0004_auto_20201027_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalentry',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='image_alt_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='image_alt_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listofhospital',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listofhospital',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listofhospital',
            name='image_alt_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='image_alt_tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
