# Generated by Django 2.2.5 on 2020-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0005_auto_20201028_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalentry',
            name='doctor_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='meta_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='meta_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitalentry',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='doctor_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='hospital_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='meta_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='meta_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='doctor_image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='meta_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='meta_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofhospitaltype',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
