# Generated by Django 2.2.5 on 2020-10-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0006_auto_20201028_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listofhospital',
        ),
        migrations.DeleteModel(
            name='Listofhospitaltype',
        ),
    ]
