# Generated by Django 2.2.5 on 2020-10-29 10:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0007_auto_20201029_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
