# Generated by Django 2.2.5 on 2020-10-29 10:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0008_hospitalbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbooking',
            name='phone',
        ),
        migrations.AddField(
            model_name='hospitalbooking',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
