# Generated by Django 2.2.5 on 2020-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0009_auto_20201029_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbooking',
            name='payment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
