# Generated by Django 2.2.5 on 2020-11-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldetails', '0011_auto_20201031_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitalbooking',
            new_name='Hospital_booking',
        ),
        migrations.RenameModel(
            old_name='Hospitalentry',
            new_name='Hospital_entry',
        ),
        migrations.RenameModel(
            old_name='Hospitaltype',
            new_name='Hospital_type',
        ),
    ]
