# Generated by Django 2.2.5 on 2020-10-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='hospital_type',
            field=models.ImageField(blank=True, default=2, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drugcartsservice',
            name='hospital_type',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pickopportunity',
            name='hospital_type',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='specialcare',
            name='hospital_type',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
