# Generated by Django 2.2.5 on 2020-10-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201026_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='asidebanner',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drugcartsservice',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pickopportunity',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specialcare',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
