# Generated by Django 2.2.5 on 2020-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201027_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='asidebanner',
            name='image_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asidebanner',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
