# Generated by Django 2.2.5 on 2020-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20201028_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
