# Generated by Django 2.2.5 on 2020-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20201031_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='hospital_type',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='drugcartsservice',
            old_name='hospital_type',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pickopportunity',
            old_name='hospital_type',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='specialcare',
            old_name='hospital_type',
            new_name='image',
        ),
        migrations.AddField(
            model_name='clinic',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drugcartsservice',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pickopportunity',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialcare',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
