# Generated by Django 2.2.5 on 2020-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
