# Generated by Django 2.2.5 on 2020-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
