# Generated by Django 2.2.5 on 2020-11-09 13:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_product_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
