# Generated by Django 2.2.5 on 2020-11-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Sub_category',
        ),
    ]
