# Generated by Django 2.2.5 on 2020-11-11 03:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0006_auto_20201111_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='url',
            new_name='image_alt_tag',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 11, 3, 50, 38, 98461, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='video_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='video_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catlog.Brand'),
        ),
    ]
