# Generated by Django 2.2.5 on 2020-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcountrycode',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofcountrycode',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
