# Generated by Django 2.2.5 on 2020-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrycode', '0002_auto_20201026_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcountrycode',
            name='image_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addcountrycode',
            name='offer_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listofcountrycode',
            name='image_alt_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listofcountrycode',
            name='offer_code',
            field=models.IntegerField(null=True),
        ),
    ]
