# Generated by Django 2.2.5 on 2020-10-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycode', '0003_auto_20201028_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcountrycode',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='listofcountrycode',
            name='offer_code',
        ),
    ]
