# Generated by Django 2.2.5 on 2020-11-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countrycode', '0004_auto_20201028_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listofcountrycode',
            new_name='Add_country_code',
        ),
        migrations.RenameModel(
            old_name='Addcountrycode',
            new_name='List_of_country_code',
        ),
    ]
