# Generated by Django 2.2.5 on 2020-10-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='order_id',
        ),
    ]
