# Generated by Django 2.2.5 on 2020-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_tracking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
