# Generated by Django 2.2.5 on 2020-11-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20201031_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Customer_name', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(null=True)),
                ('trans_id', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100, null=True)),
            ],
        ),
    ]
