# Generated by Django 2.2.5 on 2020-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
